### ISSUE TITLE
Possible bug in reactivity of table

### ISSUE THREAD

**Issue by mherb63** [cdolek/cenk-reactive-datatables#1]
The Table is not staying in sync with the Meteor collection.  For example, if I have 4 documents in my table in Mongo and I manually remove 1 of those documents, the table will update but will duplicate all existing entries.

it appears this function is not producing the differences between the datatables content and the Meteor.collection content

```     
       reactiveDataTable.difference = function(array){
       var rest = Array.prototype.concat.apply(Array.prototype, Array.prototype.slice.call(arguments, 1));

       var containsEquals = function(obj, target) {
        if (obj == null) return false;
        return _.any(obj, function(value) {
          return _.isEqual(value, target);
        });
      };

      return _.filter(array, function(value){ return ! containsEquals(rest, value); });
    };

   
```

**Comment by cdolek** [comment]
@mherb63 are you using the rowId? This is necessary for the function to figure out differences coming from the collection.

**Comment by mherb63** [comment]
yes, I saw that and I'm not writing anything to row id.  I checked my table and it has the collection object id as the row id for the table:

![image](https://cloud.githubusercontent.com/assets/1205814/23573356/5a26035a-0043-11e7-9742-dbe5da7f0bdd.png)

![image](https://cloud.githubusercontent.com/assets/1205814/23573393/98b5419e-0043-11e7-8543-e8ed95f722d2.png)

Here's what it looks like after I remove a row (via Meteor Mongo shell)
![image](https://cloud.githubusercontent.com/assets/1205814/23573475/246d422c-0044-11e7-84bb-0c91115b30db.png)

![image](https://cloud.githubusercontent.com/assets/1205814/23573487/38d9db12-0044-11e7-9893-58b62589eb7a.png)

**Comment by cdolek** [comment]
@mherb63 I'm a bit busy these days, please use [ephemer:reactive-datatables](https://github.com/ephemer/meteor-reactive-datatables) until I fix this.

**Comment by mherb63** [comment]
Wow, really?  I came here because of problems with his.  In fact, on your README.md you specifically mention that you built this repo because he was non responsive.

You should close the repo if you don't want to support it.

**Comment by cdolek** [comment]
@mherb63 please try the fix I have just committed

**Comment by mherb63** [comment]
Thank You!

Do I just uninstall the plugin and reinstall it?

**Comment by mherb63** [comment]
I just tried and it appears to be working correctly now.  I will keep testing, but close this out for now.

Thank you very much for fixing this.  Your datatables plugin was the only one I could get working with the features that I needed.
